### ISSUE TITLE
ld --nmagic segfaults

### ISSUE THREAD

**Issue by XeCycle** [XeCycle/mini-tools#2]
Seems to segfault at first instruction in `_start`.  `--nmagic` may further reduce binary size, so it's worth a try.

**Comment by MaskRay** [comment]
--nmagic works for me.

**Comment by XeCycle** [comment]
Hmm you are right...  Before creating this repo I was testing in a single file, and linking from a single .o file, which failed to run with `--nmagic`.  It also works for me here.

**Comment by MaskRay** [comment]
`--nmagic` will cause problems if there is a RW PT_LOAD (by having a `.data` section).

`--omagic` will create just one RWX PT_LOAD. It should work. However, WX PT_LOAD may not run on some systems when certain security hardening features are enabled...

Both `--nmagic` and `--omagic` disable paging (max-page-size==1). If there are two PT_LOAD program headers, the default placement likely won't work. You need a `SECTIONS` command to add appropriate alignments.

On https://maskray.me/blog/2020-12-19-lld-and-gnu-linker-incompatibilities , I mentioned

> GNU ld adds PT_PHDR and PT_INTERP together. A shared object usually does not have two program headers. In ld.lld, PT_PHDR is always added unless the address assignment makes is unsuitable to place program headers at all.

If you provide a linker script with `PHDRS` command, the PT_PHDR can be suppressed even with ld.lld...

```text
PHDRS {
  text PT_LOAD FLAGS(0x5);
  data PT_LOAD FLAGS(0x6);
}

SECTIONS {
  . = SEGMENT_START("text-segment", 0x400000) + SIZEOF_HEADERS;
  .text : { *(.text .text.*) } :text
  . = ALIGN(., CONSTANT(MAXPAGESIZE)) + . % CONSTANT(MAXPAGESIZE);
  .data : { *(.data .data.*) } :data
}
```
